server:
  port: 9527
spring:
  application:
    name: product-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///aibuy-product
    password: root
    username: root