server:
  port: 1269
spring:
  application:
    name: zuul-server
eureka:
  client:
    service-url:
      defaultZone: http://localhost:6001/eureka
  instance:
    prefer-ip-address: true
zuul:
  ignoredServices: '*'
  routes:
    plat:
      path: /plat/** #平台服务的请求路径
      serviceId: plat-service
  prefix: /services #请求前缀
